name: Dart CI

on: 
  push:
    branches:
      - master

jobs:
  build:

    runs-on: macOS-10.14
    strategy:
      matrix:
        dart: [1]
    steps:
    - uses: actions/checkout@v1
    - name: Install dart
      run: brew install dart
    - name: Run Test alarmClock
      run: dart index.dart
